name: next-level-lm
channels:
  - conda-forge
  - nvidia # nvidia channel for cuda packages
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.11 # or don't specify the version and use latest stable
  - pytorch::pytorch=2.0.1 # or don't specify the version and use latest stable
  # CUDA only on linux and windows
  - pytorch::pytorch-cuda=11.8 # [linux]
  - pytorch::pytorch-cuda=11.8 # [win]
  # This is imporant keep it
  - dargparser
  - wandb
  - lightning=2.1.*
  - transformers
  - tokenizers
  - datasets
  - loguru
  - tqdm
  - nltk
  - sentence-transformers=2.3.1
  - faiss
  - matplotlib
  - seaborn
  - einops

  # Dev dependencies
  - black
  - ruff
  - debugpy
  - ipykernel
  - ipywidgets

  # pip dependencies
  - pip
  - pip:
      - warmup-scheduler
      - pipx
      - simple_parsing
      - print-on-steroids[exceptions]

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
  # - osx-arm64 # This is for M1/M2 MacBooks
  # - linux-aarch64 # This is linux-arm64. We can build Docker images for M1/M2 Macs on top of this - won't support MPS though
  # - win-64
